package org.openmrs.module.msfcore.dhis2;

public enum PatientTrackableAttributes {
    AGE_IN_YEARS, CAUSE_OF_REFERRAL, COMMENTS_ON_REGISTRATION, CONDITION_OF_LIVING, DATE_OF_BIRTH, EDUCATION, EMPLOYMENT_STATUS, FATHER_NAME, FIRST_NAME, INITIALS_OF_CASE_MANAGER, LAST_NAME, MARITAL_STATUS, MOTHER_NAME, NATIONALITY, OLD_PATIENT_ID, PATIENT_NUMBER, PATIENT_TYPE, PHONE_NUMBER, PHONE_NUMBER_2, PROVENANCE, REFUGEE_UNHCR, REFUGEE_UNRWA, REFUGEE_STATUS, SEX, TYPE_OF_MALNUTRITION
}
